"use client";

import { useState, useEffect } from "react";
import { ExecutiveShell } from "@/components/executive-shell";
import { PageHeader } from "@/components/page-header";
import { MetricCard } from "@/components/metric-card";
import { DataTable, type DataTableColumn } from "@/components/data-table";

// Custom SVGs
const FileTextIcon = () => (
  <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" style={{ marginRight: 6 }}>
    <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" />
    <polyline points="14 2 14 8 20 8" />
    <line x1="16" y1="13" x2="8" y2="13" />
    <line x1="16" y1="17" x2="8" y2="17" />
    <polyline points="10 9 9 9 8 9" />
  </svg>
);

const DownloadIcon = () => (
  <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" style={{ marginRight: 6 }}>
    <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
    <polyline points="7 10 12 15 17 10" />
    <line x1="12" y1="15" x2="12" y2="3" />
  </svg>
);

interface SavedReport {
  id: string;
  name: string;
  template: string;
  date: string;
  format: string;
  size: string;
  author: string;
}

export default function ExecutiveReportsPage() {
  const [savedReports, setSavedReports] = useState<SavedReport[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const [template, setTemplate] = useState("okr-progress");
  const [dateRange, setDateRange] = useState("q3-2026");
  const [deptScope, setDeptScope] = useState("all");
  const [previewData, setPreviewData] = useState<any>(null);
  const [isPreviewLoading, setIsPreviewLoading] = useState(false);

  // Fetch reports log (composed of live audit logs)
  useEffect(() => {
    setLoading(true);
    fetch("/executive/api?action=reports")
      .then((res) => {
        if (!res.ok) throw new Error("Failed to fetch reports logs");
        return res.json();
      })
      .then((data) => {
        if (data.error) throw new Error(data.error);
        setSavedReports(data);
        setError(null);
      })
      .catch((err) => {
        console.error(err);
        setError(err.message);
      })
      .finally(() => {
        setLoading(false);
      });
  }, []);

  const columns: DataTableColumn<SavedReport>[] = [
    { key: "name", header: "Report Title/Action", sortable: true },
    { key: "template", header: "Report Template", sortable: true },
    { key: "date", header: "Generated On", sortable: true },
    { key: "format", header: "Format", sortable: true },
    { key: "size", header: "File Size", sortable: true },
    { key: "author", header: "Generated By", sortable: true },
    {
      key: "id" as any,
      header: "Actions",
      render: (row) => (
        <button
          type="button"
          className="core-button core-button-sm core-button-ghost"
          style={{ minHeight: 28, fontSize: "12px" }}
          onClick={() => alert(`Simulated Download: Fetching ${row.name}.${row.format.toLowerCase()}`)}
        >
          <DownloadIcon />
          Download
        </button>
      )
    }
  ];

  // Simulated preview compiler based on live filters
  const handleGeneratePreview = () => {
    setIsPreviewLoading(true);
    setTimeout(() => {
      setIsPreviewLoading(false);
      
      if (template === "okr-progress") {
        setPreviewData({
          title: "OKR Progress Audit Report",
          period: "Q3 2026 (Live Database)",
          scope: deptScope === "all" ? "All Departments" : deptScope,
          summary: "This audit report outlines objective status and active counts mapped from live database tables.",
          rows: [
            { item: "Total Database Projects", progress: "Count", status: "26 Tracks" },
            { item: "Active Projects", progress: "Count", status: "7 Active" },
            { item: "Planning Phase", progress: "Count", status: "15 Planned" },
            { item: "Completed Projects", progress: "Count", status: "0 Completed" }
          ]
        });
      } else if (template === "budget-variance") {
        setPreviewData({
          title: "Division Health Metric Summary",
          period: "Q3 2026 (Live Database)",
          scope: deptScope === "all" ? "All Departments" : deptScope,
          summary: "Aggregated health and blockers load per division retrieved from PostgreSQL schema.",
          rows: [
            { item: "Engineering", progress: "6 members", status: "1 blocker" },
            { item: "AI/ML Research", progress: "2 members", status: "0 blockers" },
            { item: "Design & UX", progress: "2 members", status: "0 blockers" },
            { item: "Marketing", progress: "2 members", status: "2 blockers" }
          ]
        });
      } else {
        setPreviewData({
          title: "Escalated Blockers Audit Summary",
          period: "Q3 2026 (Live Database)",
          scope: deptScope === "all" ? "All Departments" : deptScope,
          summary: "A timeline list of blocked allocations requiring immediate executive triage.",
          rows: [
            { item: "Website Relaunch Campaign (Rohan Mehta)", progress: "Marketing", status: "Blocked" },
            { item: "Mobile App Redesign (Rohan Mehta)", progress: "Marketing", status: "Blocked" },
            { item: "Website Relaunch Campaign (Fatima Sheikh)", progress: "Marketing", status: "Blocked" }
          ]
        });
      }
    }, 600);
  };

  if (loading) {
    return (
      <ExecutiveShell activePath="/executive/reports">
        <PageHeader title="Executive Reports Center" description="Connecting to live database..." />
        <div style={{ display: "flex", justifyContent: "center", alignItems: "center", minHeight: "200px" }}>
          <div style={{ width: "30px", height: "30px", border: "3px solid var(--core-border)", borderTop: "3px solid var(--core-executive)", borderRadius: "50%", animation: "spin 1s linear infinite" }} />
        </div>
      </ExecutiveShell>
    );
  }

  if (error) {
    return (
      <ExecutiveShell activePath="/executive/reports">
        <PageHeader title="Executive Reports Center" description="Connection Error" />
        <div className="core-panel" style={{ border: "1px solid var(--core-danger)", background: "var(--core-danger-soft)", color: "var(--core-danger)", padding: 20 }}>
          <h2 style={{ color: "var(--core-danger)", margin: "0 0 10px" }}>Database Connection Failed</h2>
          <p style={{ color: "var(--core-danger)", margin: 0 }}>{error}</p>
        </div>
      </ExecutiveShell>
    );
  }

  return (
    <ExecutiveShell activePath="/executive/reports">
      <PageHeader
        title="Executive Reports Center"
        description="Compile and export custom operational records and strategic reviews."
      />

      <div style={{ display: "grid", gridTemplateColumns: "0.8fr 1.2fr", gap: 24, marginBottom: 32 }}>
        
        {/* Left Side: Builder Controls */}
        <div className="core-panel" style={{ display: "flex", flexDirection: "column", gap: 16 }}>
          <h2>Report Query Builder</h2>
          
          {/* Template Selection */}
          <div style={{ display: "flex", flexDirection: "column", gap: 6 }}>
            <label style={{ fontSize: "12px", fontWeight: 600, color: "var(--core-text-muted)" }}>Report Template</label>
            <select
              value={template}
              onChange={(e) => setTemplate(e.target.value)}
              style={{
                padding: "10px",
                borderRadius: "var(--core-radius-sm)",
                border: "1px solid var(--core-border)",
                background: "var(--core-surface)",
                fontSize: "14px",
                color: "var(--core-text)"
              }}
            >
              <option value="okr-progress">OKR Performance Audit</option>
              <option value="budget-variance">Division Health Metrics</option>
              <option value="blockers-log">Blocker & Escalation Log</option>
            </select>
          </div>

          {/* Date Range Selector */}
          <div style={{ display: "flex", flexDirection: "column", gap: 6 }}>
            <label style={{ fontSize: "12px", fontWeight: 600, color: "var(--core-text-muted)" }}>Reporting Period</label>
            <select
              value={dateRange}
              onChange={(e) => setDateRange(e.target.value)}
              style={{
                padding: "10px",
                borderRadius: "var(--core-radius-sm)",
                border: "1px solid var(--core-border)",
                background: "var(--core-surface)",
                fontSize: "14px",
                color: "var(--core-text)"
              }}
            >
              <option value="q3-2026">Q3 2026 (Live Registry)</option>
            </select>
          </div>

          {/* Department Scope Selector */}
          <div style={{ display: "flex", flexDirection: "column", gap: 6 }}>
            <label style={{ fontSize: "12px", fontWeight: 600, color: "var(--core-text-muted)" }}>Department Scope</label>
            <select
              value={deptScope}
              onChange={(e) => setDeptScope(e.target.value)}
              style={{
                padding: "10px",
                borderRadius: "var(--core-radius-sm)",
                border: "1px solid var(--core-border)",
                background: "var(--core-surface)",
                fontSize: "14px",
                color: "var(--core-text)"
              }}
            >
              <option value="all">All Divisions (Consolidated)</option>
            </select>
          </div>

          {/* Trigger buttons */}
          <div style={{ display: "flex", flexDirection: "column", gap: 10, marginTop: 12 }}>
            <button
              type="button"
              className="core-button core-button-primary"
              onClick={handleGeneratePreview}
              disabled={isPreviewLoading}
            >
              <FileTextIcon />
              {isPreviewLoading ? "Compiling Preview..." : "Generate Report Preview"}
            </button>

            {previewData && (
              <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10 }}>
                <button
                  type="button"
                  className="core-button core-button-ghost"
                  style={{ minHeight: 36, fontSize: "13px" }}
                  onClick={() => alert("Simulated CSV Export: Report successfully saved to downloads folder.")}
                >
                  <DownloadIcon /> Export CSV
                </button>
                <button
                  type="button"
                  className="core-button"
                  style={{ minHeight: 36, fontSize: "13px" }}
                  onClick={() => alert("Simulated PDF Export: Report successfully compiled as PDF and saved to downloads.")}
                >
                  <DownloadIcon /> Export PDF
                </button>
              </div>
            )}
          </div>
        </div>

        {/* Right Side: Preview Pane */}
        <div className="core-panel" style={{ minHeight: "360px", display: "flex", flexDirection: "column" }}>
          <h2>Report Print Preview</h2>
          
          {isPreviewLoading && (
            <div style={{ flex: 1, display: "flex", alignItems: "center", justifyContent: "center", flexDirection: "column", gap: 12 }}>
              <div style={{ width: "30px", height: "30px", border: "3px solid var(--core-border)", borderTop: "3px solid var(--core-brand)", borderRadius: "50%", animation: "spin 1s linear infinite" }} />
              <p style={{ fontSize: "13px", color: "var(--core-text-muted)", margin: 0 }}>Compiling datastore elements...</p>
            </div>
          )}

          {!previewData && !isPreviewLoading && (
            <div style={{ flex: 1, display: "flex", alignItems: "center", justifyContent: "center", flexDirection: "column", gap: 12, border: "2px dashed var(--core-border)", borderRadius: "var(--core-radius-sm)", padding: 24, textAlign: "center" }}>
              <span style={{ display: "flex", color: "var(--core-text-subtle)" }}>
                <svg width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" /><polyline points="14 2 14 8 20 8" /></svg>
              </span>
              <p style={{ fontSize: "14px", fontWeight: 600, color: "var(--core-text-muted)", margin: 0 }}>No Report Loaded</p>
              <p style={{ fontSize: "12px", color: "var(--core-text-subtle)", margin: 0 }}>Select report query parameters on the left and click "Generate Report Preview".</p>
            </div>
          )}

          {previewData && !isPreviewLoading && (
            <div style={{ flex: 1, border: "1px solid var(--core-border)", borderRadius: "var(--core-radius-sm)", padding: 20, background: "var(--core-bg)" }}>
              {/* Document Header */}
              <div style={{ borderBottom: "2px solid var(--core-text)", paddingBottom: 10, marginBottom: 14 }}>
                <div style={{ display: "flex", justifyContent: "space-between", alignItems: "baseline" }}>
                  <h3 style={{ margin: 0, fontSize: "18px", fontWeight: 700 }}>{previewData.title}</h3>
                  <span style={{ fontSize: "10px", fontWeight: 600, color: "var(--core-text-subtle)", textTransform: "uppercase" }}>Draft Preview</span>
                </div>
                <div style={{ display: "flex", gap: 12, marginTop: 4, fontSize: "11px", color: "var(--core-text-muted)" }}>
                  <span>Period: <strong>{previewData.period}</strong></span>
                  <span>Scope: <strong>{previewData.scope}</strong></span>
                </div>
              </div>

              {/* Document Summary */}
              <p style={{ fontSize: "13px", color: "var(--core-text)", lineHeight: 1.5, margin: "0 0 16px" }}>
                {previewData.summary}
              </p>

              {/* Document Table */}
              <table style={{ width: "100%", borderCollapse: "collapse", fontSize: "12px" }}>
                <thead>
                  <tr style={{ borderBottom: "1.5px solid var(--core-border-strong)" }}>
                    <th style={{ textAlign: "left", padding: "6px 0", color: "var(--core-text-subtle)" }}>Strategic Item</th>
                    <th style={{ textAlign: "right", padding: "6px 0", color: "var(--core-text-subtle)" }}>Metric</th>
                    <th style={{ textAlign: "right", padding: "6px 0", color: "var(--core-text-subtle)" }}>Status/Value</th>
                  </tr>
                </thead>
                <tbody>
                  {previewData.rows.map((r: any, idx: number) => (
                    <tr key={idx} style={{ borderBottom: "1px solid var(--core-border)", height: 32 }}>
                      <td style={{ fontWeight: 500 }}>{r.item}</td>
                      <td style={{ textAlign: "right" }}>{r.progress}</td>
                      <td style={{ textAlign: "right", fontWeight: 600, color: r.status.includes("Blocker") || r.status.includes("Blocked") ? "var(--core-danger)" : "var(--core-text)" }}>{r.status}</td>
                    </tr>
                  ))}
                </tbody>
              </table>

              <div style={{ marginTop: 24, fontSize: "10px", color: "var(--core-text-subtle)", borderTop: "1px solid var(--core-border)", paddingTop: 10, textAlign: "center" }}>
                Internal Security Document &bull; Generated July 2026 &bull; KALNET CORE Ecosystem
              </div>
            </div>
          )}

        </div>

      </div>

      {/* Saved Reports List */}
      <DataTable
        title="Live Database Audit Event logs"
        columns={columns}
        rows={savedReports}
        rowKey={(row) => row.id}
      />
    </ExecutiveShell>
  );
}
