"use client";

import { useState } from "react";
import { ExecutiveShell } from "@/components/executive-shell";
import { PageHeader } from "@/components/page-header";
import { MetricCard } from "@/components/metric-card";
import { DataTable, type DataTableColumn } from "@/components/data-table";

// Custom SVGs
const FileTextIcon = () => (
  <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" style={{ marginRight: 6 }}>
    <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" />
    <polyline points="14 2 14 8 20 8" />
    <line x1="16" y1="13" x2="8" y2="13" />
    <line x1="16" y1="17" x2="8" y2="17" />
    <polyline points="10 9 9 9 8 9" />
  </svg>
);

const DownloadIcon = () => (
  <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" style={{ marginRight: 6 }}>
    <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
    <polyline points="7 10 12 15 17 10" />
    <line x1="12" y1="15" x2="12" y2="3" />
  </svg>
);

const SearchIcon = () => (
  <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
    <circle cx="11" cy="11" r="8" />
    <line x1="21" y1="21" x2="16.65" y2="16.65" />
  </svg>
);

interface SavedReport {
  id: string;
  name: string;
  template: string;
  date: string;
  format: "PDF" | "CSV";
  size: string;
  author: string;
}

export default function ExecutiveReportsPage() {
  const [template, setTemplate] = useState("okr-progress");
  const [dateRange, setDateRange] = useState("q3-2026");
  const [deptScope, setDeptScope] = useState("all");
  const [previewData, setPreviewData] = useState<any>(null);
  const [isPreviewLoading, setIsPreviewLoading] = useState(false);

  const savedReports: SavedReport[] = [
    { id: "rep-1", name: "Q2 Core Performance Review", template: "Company OKR Progress", date: "July 01, 2026", format: "PDF", size: "1.4 MB", author: "Michael Kim (CEO)" },
    { id: "rep-2", name: "June Blocker Escalation Audit", template: "Blocker Resolution History", date: "June 30, 2026", format: "CSV", size: "412 KB", author: "David L. (Eng Head)" },
    { id: "rep-3", name: "H1 Budget Variance Summary", template: "Departmental Budget Audit", date: "June 15, 2026", format: "PDF", size: "2.8 MB", author: "Jessica T. (Sales Head)" }
  ];

  const columns: DataTableColumn<SavedReport>[] = [
    { key: "name", header: "Report Title", sortable: true },
    { key: "template", header: "Report Template", sortable: true },
    { key: "date", header: "Generated On", sortable: true },
    { key: "format", header: "Format", sortable: true },
    { key: "size", header: "File Size", sortable: true },
    { key: "author", header: "Generated By", sortable: true },
    {
      key: "id" as any,
      header: "Actions",
      render: (row) => (
        <button
          type="button"
          className="core-button core-button-sm core-button-ghost"
          style={{ minHeight: 28, fontSize: "12px" }}
          onClick={() => alert(`Simulated Download: Fetching ${row.name}.${row.format.toLowerCase()}`)}
        >
          <DownloadIcon />
          Download
        </button>
      )
    }
  ];

  // Simulated preview compiler
  const handleGeneratePreview = () => {
    setIsPreviewLoading(true);
    setTimeout(() => {
      setIsPreviewLoading(false);
      
      if (template === "okr-progress") {
        setPreviewData({
          title: "OKR Progress Audit Report",
          period: dateRange === "q3-2026" ? "Q3 2026" : "Full Year 2026",
          scope: deptScope === "all" ? "All Departments" : deptScope,
          summary: "This audit report outlines objective progress against corporate key targets.",
          rows: [
            { item: "Expand to EMEA", progress: "45%", status: "On Track" },
            { item: "AI Integration", progress: "20%", status: "At Risk" },
            { item: "Cost Reduction", progress: "85%", status: "On Track" },
            { item: "Cloud Migration", progress: "92%", status: "Completed" }
          ]
        });
      } else if (template === "budget-variance") {
        setPreviewData({
          title: "Department Budget Variance Audit",
          period: dateRange === "q3-2026" ? "Q3 2026" : "Full Year 2026",
          scope: deptScope === "all" ? "All Departments" : deptScope,
          summary: "Fiscal monitoring representing capital variance of operational divisions.",
          rows: [
            { item: "Engineering", progress: "$450k", status: "-1.2% (Under)" },
            { item: "AI/ML Research", progress: "$320k", status: "+4.5% (Over)" },
            { item: "Product Management", progress: "$120k", status: "-0.5% (Under)" },
            { item: "IT Operations", progress: "$95k", status: "+7.2% (Over)" }
          ]
        });
      } else {
        setPreviewData({
          title: "Critical Blocker Escalations Summary",
          period: dateRange === "q3-2026" ? "Q3 2026" : "Full Year 2026",
          scope: deptScope === "all" ? "All Departments" : deptScope,
          summary: "A timeline list of blocking roadblocks affecting deliverable schedules.",
          rows: [
            { item: "AI Compute Capacity Limit", progress: "AI Research", status: "Critical Blocker" },
            { item: "GDPR Legal Auditing", progress: "EMEA Expansion", status: "SLA Warning" },
            { item: "RDS Database Port Latency", progress: "Cloud Migration", status: "Resolved" }
          ]
        });
      }
    }, 800);
  };

  return (
    <ExecutiveShell activePath="/executive/reports">
      <PageHeader
        title="Executive Reports Center"
        description="Compile and export custom operational records, variance audits, and strategic reviews."
      />

      <div style={{ display: "grid", gridTemplateColumns: "0.8fr 1.2fr", gap: 24, marginBottom: 32 }}>
        
        {/* Left Side: Builder Controls */}
        <div className="core-panel" style={{ display: "flex", flexDirection: "column", gap: 16 }}>
          <h2>Report Query Builder</h2>
          
          {/* Template Selection */}
          <div style={{ display: "flex", flexDirection: "column", gap: 6 }}>
            <label style={{ fontSize: "12px", fontWeight: 600, color: "var(--core-text-muted)" }}>Report Template</label>
            <select
              value={template}
              onChange={(e) => setTemplate(e.target.value)}
              style={{
                padding: "10px",
                borderRadius: "var(--core-radius-sm)",
                border: "1px solid var(--core-border)",
                background: "var(--core-surface)",
                fontSize: "14px",
                color: "var(--core-text)"
              }}
            >
              <option value="okr-progress">OKR Performance Audit</option>
              <option value="budget-variance">Departmental Budget Variance</option>
              <option value="blockers-log">Blocker & Escalation Log</option>
            </select>
          </div>

          {/* Date Range Selector */}
          <div style={{ display: "flex", flexDirection: "column", gap: 6 }}>
            <label style={{ fontSize: "12px", fontWeight: 600, color: "var(--core-text-muted)" }}>Reporting Period</label>
            <select
              value={dateRange}
              onChange={(e) => setDateRange(e.target.value)}
              style={{
                padding: "10px",
                borderRadius: "var(--core-radius-sm)",
                border: "1px solid var(--core-border)",
                background: "var(--core-surface)",
                fontSize: "14px",
                color: "var(--core-text)"
              }}
            >
              <option value="q3-2026">Q3 2026 (July - September)</option>
              <option value="full-2026">Full Year 2026</option>
            </select>
          </div>

          {/* Department Scope Selector */}
          <div style={{ display: "flex", flexDirection: "column", gap: 6 }}>
            <label style={{ fontSize: "12px", fontWeight: 600, color: "var(--core-text-muted)" }}>Department Scope</label>
            <select
              value={deptScope}
              onChange={(e) => setDeptScope(e.target.value)}
              style={{
                padding: "10px",
                borderRadius: "var(--core-radius-sm)",
                border: "1px solid var(--core-border)",
                background: "var(--core-surface)",
                fontSize: "14px",
                color: "var(--core-text)"
              }}
            >
              <option value="all">All Divisions (Consolidated)</option>
              <option value="Engineering">Engineering only</option>
              <option value="AI/ML Research">AI/ML Research only</option>
            </select>
          </div>

          {/* Trigger buttons */}
          <div style={{ display: "flex", flexDirection: "column", gap: 10, marginTop: 12 }}>
            <button
              type="button"
              className="core-button core-button-primary"
              onClick={handleGeneratePreview}
              disabled={isPreviewLoading}
            >
              <FileTextIcon />
              {isPreviewLoading ? "Compiling Preview..." : "Generate Report Preview"}
            </button>

            {previewData && (
              <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10 }}>
                <button
                  type="button"
                  className="core-button core-button-ghost"
                  style={{ minHeight: 36, fontSize: "13px" }}
                  onClick={() => alert("Simulated CSV Export: Report successfully saved to downloads folder.")}
                >
                  <DownloadIcon /> Export CSV
                </button>
                <button
                  type="button"
                  className="core-button"
                  style={{ minHeight: 36, fontSize: "13px" }}
                  onClick={() => alert("Simulated PDF Export: Report successfully compiled as PDF and saved to downloads.")}
                >
                  <DownloadIcon /> Export PDF
                </button>
              </div>
            )}
          </div>
        </div>

        {/* Right Side: Preview Pane */}
        <div className="core-panel" style={{ minHeight: "360px", display: "flex", flexDirection: "column" }}>
          <h2>Report Print Preview</h2>
          
          {isPreviewLoading && (
            <div style={{ flex: 1, display: "flex", alignItems: "center", justifyContent: "center", flexDirection: "column", gap: 12 }}>
              <div style={{ width: "30px", height: "30px", border: "3px solid var(--core-border)", borderTop: "3px solid var(--core-brand)", borderRadius: "50%", animation: "spin 1s linear infinite" }} />
              <p style={{ fontSize: "13px", color: "var(--core-text-muted)", margin: 0 }}>Compiling datastore elements...</p>
            </div>
          )}

          {!previewData && !isPreviewLoading && (
            <div style={{ flex: 1, display: "flex", alignItems: "center", justifyContent: "center", flexDirection: "column", gap: 12, border: "2px dashed var(--core-border)", borderRadius: "var(--core-radius-sm)", padding: 24, textAlign: "center" }}>
              <span style={{ display: "flex", color: "var(--core-text-subtle)" }}>
                <svg width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" /><polyline points="14 2 14 8 20 8" /></svg>
              </span>
              <p style={{ fontSize: "14px", fontWeight: 600, color: "var(--core-text-muted)", margin: 0 }}>No Report Loaded</p>
              <p style={{ fontSize: "12px", color: "var(--core-text-subtle)", margin: 0 }}>Select report query parameters on the left and click "Generate Report Preview".</p>
            </div>
          )}

          {previewData && !isPreviewLoading && (
            <div style={{ flex: 1, border: "1px solid var(--core-border)", borderRadius: "var(--core-radius-sm)", padding: 20, background: "var(--core-bg)" }}>
              {/* Document Header */}
              <div style={{ borderBottom: "2px solid var(--core-text)", paddingBottom: 10, marginBottom: 14 }}>
                <div style={{ display: "flex", justifyContent: "space-between", alignItems: "baseline" }}>
                  <h3 style={{ margin: 0, fontSize: "18px", fontWeight: 700 }}>{previewData.title}</h3>
                  <span style={{ fontSize: "10px", fontWeight: 600, color: "var(--core-text-subtle)", textTransform: "uppercase" }}>Draft Preview</span>
                </div>
                <div style={{ display: "flex", gap: 12, marginTop: 4, fontSize: "11px", color: "var(--core-text-muted)" }}>
                  <span>Period: <strong>{previewData.period}</strong></span>
                  <span>Scope: <strong>{previewData.scope}</strong></span>
                </div>
              </div>

              {/* Document Summary */}
              <p style={{ fontSize: "13px", color: "var(--core-text)", lineHeight: 1.5, margin: "0 0 16px" }}>
                {previewData.summary}
              </p>

              {/* Document Table */}
              <table style={{ width: "100%", borderCollapse: "collapse", fontSize: "12px" }}>
                <thead>
                  <tr style={{ borderBottom: "1.5px solid var(--core-border-strong)" }}>
                    <th style={{ textAlign: "left", padding: "6px 0", color: "var(--core-text-subtle)" }}>Strategic Item</th>
                    <th style={{ textAlign: "right", padding: "6px 0", color: "var(--core-text-subtle)" }}>Metric</th>
                    <th style={{ textAlign: "right", padding: "6px 0", color: "var(--core-text-subtle)" }}>Status/Value</th>
                  </tr>
                </thead>
                <tbody>
                  {previewData.rows.map((r: any, idx: number) => (
                    <tr key={idx} style={{ borderBottom: "1px solid var(--core-border)", height: 32 }}>
                      <td style={{ fontWeight: 500 }}>{r.item}</td>
                      <td style={{ textAlign: "right" }}>{r.progress}</td>
                      <td style={{ textAlign: "right", fontWeight: 600, color: r.status.includes("Risk") || r.status.includes("Blocker") || r.status.includes("Over") ? "var(--core-danger)" : "var(--core-text)" }}>{r.status}</td>
                    </tr>
                  ))}
                </tbody>
              </table>

              <div style={{ marginTop: 24, fontSize: "10px", color: "var(--core-text-subtle)", borderTop: "1px solid var(--core-border)", paddingTop: 10, textAlign: "center" }}>
                Internal Security Document &bull; Generated July 2026 &bull; KALNET CORE Ecosystem
              </div>
            </div>
          )}

        </div>

      </div>

      {/* Saved Reports List */}
      <DataTable
        title="Previously Generated Executive Reports"
        columns={columns}
        rows={savedReports}
        rowKey={(row) => row.id}
      />
    </ExecutiveShell>
  );
}
